[package]
name = "storekey"
publish = true
edition = "2021"
version = "0.4.1"
authors = ["Tobie Morgan Hitchcock <tobie@surrealdb.com>", "Michal Hornicky <mhornick@redhat.com>", "Dan Burkert <dan@danburkert.com>"]
description = "Lexicographic sort-order preserving binary encoding format for key-value stores"
repository = "https://github.com/surrealdb/storekey"
homepage = "https://github.com/surrealdb/storekey"
keywords = ["database", "encoding", "key-value", "kv-store", "serialization"]
categories = ["encoding"]
license = "Apache-2.0"

[dependencies]
byteorder = "1.4.3"
memchr = "2.5.0"
serde = { version = "1.0.158", features = ["derive"] }
thiserror = "1.0.40"
